version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: ${USER_HASH}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=wg.voytivit.ru #optional
      - SERVERPORT=${PORT} #optional
      - PEERS=${PEERS} #optional
      - PEERDNS=10.13.${IP}.1 #optional
      - INTERNAL_SUBNET=10.13.${IP}.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - ${PORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
